import type { NextPage } from 'next'
import Head from 'next/head'
import Heroe from '../components/Heroe'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heroe />

      {/* Product
        
        Overview
        Pricing
        Marketplace
        Features
        Integrations

        Company

        About
        Team
        Blog
        Careers

        Connect

        Contact
        Newsletter
        LinkedIn

        Login
        Sign Up

        A modern publishing platform
        Grow your audience and build your online brand

        Start for Free
        Learn More


        <div className="attribution">
          Challenge by
          <Link href="https://www.frontendmentor.io?ref=challenge">
            <a>Frontend Mentor</a>
          </Link>
          Coded by
          <Link href='/#'>
            <a>Zitha Chitra</a>.
          </Link>
        </div> */}


    </div>
  )
      
}

export default Home
